### ISSUE TITLE
关于个人阅读文献和写论文使用的工具 | 追梦人的博客

### ISSUE THREAD

**Issue by imdreamer2018** [imdreamer2018/blog#6]
https://www.dreamer.im/2020/03/01/%E9%9A%8F%E7%AC%94/%E5%85%B3%E4%BA%8E%E4%B8%AA%E4%BA%BA%E9%98%85%E8%AF%BB%E8%AE%BA%E6%96%87%E5%92%8C%E5%86%99%E8%AE%BA%E6%96%87%E4%BD%BF%E7%94%A8%E7%9A%84%E5%B7%A5%E5%85%B7/

**Comment by imdreamer2018** [comment]
如有错误，烦请指正。

**Comment by JoeyBling** [comment]
Good job

**Comment by andy491** [comment]
中文有知网研学（E-study），没你这些好哈哈哈
